---
## from galaxy
#- src: yatesr.timezone

# from github
- src: jkanclerz.deploy-project
  path: roles/
  version: v0.9.2
  name: deploy.project

- src: jkanclerz.deploy-finalize
  path: roles/
  version: v0.9.2
  name: deploy.finalize

- src: jkanclerz.deploy-setup
  path: roles/
  version: v0.2
  name: deploy.setup

- src: jkanclerz.deploy-project-php-symfony
  path: roles/
  version: v0.1
  name: deploy.project.php.symfony